<start> ::= <statements> ;;

<statements> ::= 100 <statements> <statement> | <statement> ;;

<statement> ::= <loop> | <commands> ;;

<loop> ::= "[" <commands> "]" ;;

<commands> ::= 10 <commands> <command> | <command> ;;

<command> ::= 5 <ptrgroup> <arithmgroup> | <io> ;;

<ptrinc> ::= 5 <ptrinc> ">" | ">" ;;

<ptrdec> ::= 5 <ptrdec> "<" | "<" ;;

<valinc> ::= 5 <valinc> "+" | "+" ;;

<valdec> ::= 5 <valdec> "+" | "-" ;;

<ptrgroup> ::= 5 <ptrinc> | <ptrdec> ;;

<arithmgroup> ::= 5 <valinc> | <valdec> ;;

<io> ::= "." | ","
